---
- name: Deploy Flask App to Target EC2
  hosts: all
  become: yes
  tasks:
    - name: Pull image from Docker Hub
      community.docker.docker_image:
        name: "{{ docker_user }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull
        state: present

    - name: Ensure old container is gone
      community.docker.docker_container:
        name: "{{ image_name }}"
        state: absent

    - name: Start the new application container
      community.docker.docker_container:
        name: "{{ image_name }}"
        image: "{{ docker_user }}/{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "4000:5000"

    - name: Wait for application to be ready (Local Check)
      ansible.builtin.uri:
        url: "http://localhost:4000"  # This is the target server checking itself
        status_code: 200
      register: web_check
      until: web_check.status == 200
      retries: 6
      delay: 10

